version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - MONGODB_HOST=mongo
      - MQ_HOST=activemq
      - MQ_PORT=61613
      - MQ_USER=system
      - MQ_PASS=manager
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - activemq
    command: ["./start.sh"]
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  activemq:
    container_name: activemq
    image: webcenter/activemq
    ports:
      - "61613:61613"
      - "8161:8161"
