version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - MONGODB_HOST=mongo
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
