version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
      - activemq
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  activemq:
    container_name: activemq
    image: webcenter/activemq
    ports:
      - "61613:61613"
      - "8161:8161"
