version: "3"
services:
  app:
    image: finizco/nginx-node:latest
    ports:
    - "8080:8080"
    environment:
    - NODE_PORT=3000
    - NODE_MODE=prod
    volumes:
    - ./:/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  activemq:
    container_name: activemq
    image: webcenter/activemq
    ports:
      - "61613:61613"
      - "8161:8161"
