version: "3"
services:
  mockiato-app:
    container_name: mockiato-app
    restart: always
    build: .
    environment:
      - MONGODB_HOST=mongo
      - MOCKIATO_NODES=4
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

