module.exports = Object.freeze({
    SPACE: ' ',
    HTTP: 'HTTP',
    SOAP: 'SOAP',
    REST: 'REST',
    POST: 'POST',
    XML: 'XML',
    JSON: 'JSON',
    QUESTION_MARK: '?',
    AMPERSAND: '&',
    EQUAL_SIGN: '=',
    WRONG_FILE_ENDING_OR_TYPE_ERR_MSG: 'All files name should end with either -req or -rsp',
    ALL_REST_METHODS: '["GET", "POST", "UPDATE", "DELETE", "PATCH", "PUT", "HEAD", "CONNECT", "OPTIONS", "TRACE"]',
    NOT_EVEN_ERR_MSG: 'Number of files in your uploaded zip is not even.',
    REQ_RES_FILENAME_DIFF_ERR_MSG: 'Any of request/response file in uploaded zip have different names.',
    NOT_REST_TYPE_ERR_MSG: 'Request file in uploaded zip is not a REST type request file.',
    NOT_SOAP_TYPE_ERR_MSG: 'Request file in uploaded zip is not a SOAP type request file.',
    SOAP_FILE_STARTSWITH: '<soap:Envelope',
    REQ_FILE_END: '-req',
    RSP_FILE_END: '-rsp'
});