module.exports = Object.freeze({
    //below constants for bulk upload parser.js
    SPACE: ' ',
    HTTP: 'HTTP',
    SOAP: 'SOAP',
    REST: 'REST',
    POST: 'POST',
    XML: 'XML',
    JSON: 'JSON',
    PLAIN: 'PLAIN',
    QUESTION_MARK: '?',
    AMPERSAND: '&',
    EQUAL_SIGN: '=',
    WRONG_FILE_ENDING_ERR_MSG: 'All files name should end with either -req or -rsp',
    ALL_REST_METHODS: '["GET", "POST", "UPDATE", "DELETE", "PATCH", "PUT", "HEAD", "CONNECT", "OPTIONS", "TRACE"]',
    NOT_EVEN_ERR_MSG: 'Number of files in your uploaded zip is not even.',
    REQ_RES_FILENAME_DIFF_ERR_MSG: 'Any of request/response file in uploaded zip have different names.',
    NOT_SOAP_TYPE_ERR_MSG: 'There is no soap Envelope xml <tag> in one of req/rsp file in uploaded zip.',
    SOAP_FILE_STARTSWITH1: '<soap:Envelope ',
    SOAP_FILE_STARTSWITH2: '<soapenv:Envelope ',
    XML_DECLARATION: '<?xml version="1.0" encoding="UTF-8"?>',
    REQ_FILE_END: '-req',
    RSP_FILE_END: '-rsp',
    APPLICATION_XML: 'application/xml',
    TEXT_XML: 'text/xml',
    APPLICATION_JSON: 'application/json',
    TEXT_PLAIN: 'text/plain',
    //below constants for app.js of express framework.
    ORG_USR_REGISTER_VIEW: '<!DOCTYPE html><html><head><title>Mockiato ☕</title>	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">		<link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></head><body><div class="container"><nav class="navbar navbar-inverse"><div class="navbar-header lightFont"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar"><span class="icon-bar" /><span class="icon-bar" /><span class="icon-bar" /></button><a class="navbar-brand" href="/#helppage"><strong>Mockiato ☕</strong></a></div></nav></div><div><div class="vertical-center"><div class="loginform"><label>You already registered!!</label></br></br>You are using Mockiato in your organziation. Please login with your organization credentials.<br/><br/><a href="/"><button class="btn btn-lg btn-primary center-block">Back</button><br></div></div></div></body></html>',
});