module.exports = Object.freeze({
    SPACE: ' ',
    HTTP: 'HTTP',
    SOAP: 'SOAP',
    REST: 'REST',
    POST: 'POST',
    XML: 'XML',
    JSON: 'JSON',
    PLAIN: 'PLAIN',
    QUESTION_MARK: '?',
    AMPERSAND: '&',
    EQUAL_SIGN: '=',
    WRONG_FILE_ENDING_ERR_MSG: 'All files name should end with either -req or -rsp',
    ALL_REST_METHODS: '["GET", "POST", "UPDATE", "DELETE", "PATCH", "PUT", "HEAD", "CONNECT", "OPTIONS", "TRACE"]',
    NOT_EVEN_ERR_MSG: 'Number of files in your uploaded zip is not even.',
    REQ_RES_FILENAME_DIFF_ERR_MSG: 'Any of request/response file in uploaded zip have different names.',
    NOT_SOAP_TYPE_ERR_MSG: 'There is no soap Envelope xml <tag> in one of req/rsp file in uploaded zip.',
    SOAP_FILE_STARTSWITH1: '<soap:Envelope',
    SOAP_FILE_STARTSWITH2: '<soapenv:Envelope',
    REQ_FILE_END: '-req',
    RSP_FILE_END: '-rsp',
    APPLICATION_XML: 'application/xml',
    TEXT_XML: 'text/xml',
    APPLICATION_JSON: 'application/json',
    TEXT_PLAIN: 'text/plain'
});